(*
Defs.inc
--------
Begin: 2006/03/01
Last revision: $Date: 2010-04-08 17:56:47 $ $Author: areeves $
Version: $Revision: 1.1 $
Project: NAADSM
Website: http://www.naadsm.org
Author: Aaron Reeves <Aaron.Reeves@colostate.edu>
--------------------------------------------------
Copyright (C) 2010 Animal Population Health Institute, Colorado State University

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General
Public License as published by the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
*)


(* This is an empty defs file to satisfy a compiler file requirement ({$INCLUDE Defs.inc}) in unit 
   ..\Delphi_libs\general_purpose\I88n.pas. To install one of the APHI Controls into the Delphi IDE
   put a copy of this empty defs file in the folder where the component's .dpk file is located. 
   The general_purpose library must be in the Delphi library path prior to installing an APHI IDE component.
*)


// Define the following symbol to display and use the debugging window.
//{$DEFINE DEBUG}


